version: '3.8'

services:
  backend:
    build:
      context: ./prueba-backend
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres

  frontend:
    build:
      context: ./prueba-frontend
    ports:
      - "80:80"  
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: COMPANY_BD
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: